'use client'
import { useState } from 'react'
import { Copy, CheckCheck, ChevronDown, ChevronUp, Rocket, ArrowRight } from 'lucide-react'
import { cn } from '@/lib/utils'
import { Button } from '@/components/ui/Button'
import type { WizardData } from './types'

interface StepReviewProps {
  data: WizardData
  onDeploy: () => void
  deploying: boolean
}

/* ─────────────────────────── config generators ─────────────────────────── */

function generateSnareYaml(data: WizardData): string {
  const { step1, step2 } = data
  const decoySlug = (step2.name || 'unnamed-decoy').toLowerCase().replace(/\s+/g, '-')
  return `# SNARE Configuration — Generated by HoneyForge Clone Studio
# Decoy: ${step2.name || 'Unnamed Decoy'}
# Source: ${step1.url || 'N/A'}
# WARNING: Deploy only on assets you own or are authorized to test

port: 8080
dir: /var/snap/
tanner: http://tanner:8090
page-dir: /opt/honeyforge/decoys/${decoySlug}
clone-url: "${step1.url || ''}"
clone-strategy: "${step1.cloneType}"
debug: false
slurp-delay: 0.0
slurp-size-limit: 5

decoy:
  name: "${step2.name || ''}"
  category: "${step2.category || ''}"
  department: "${step2.department || ''}"
  business_owner: "${step2.businessOwner || ''}"
  tags: [${(step2.tags || '').split(',').map((t) => `"${t.trim()}"`).filter(Boolean).join(', ')}]

rate_limit:
  enabled: true
  max_requests: 200
  window_seconds: 60

auth:
  required: ${step1.authRequired}${step1.authRequired ? `\n  username: "${step1.username}"` : ''}

tls:
  enabled: false
`
}

function generateTannerJson(data: WizardData): string {
  const { step3, step4 } = data
  const obj = {
    server:  { host: '0.0.0.0', port: 8090, debug: false, timeout: 30 },
    plugins: {
      sql_injection:     { enabled: step3.sqlInjection },
      xss:               { enabled: step3.xss },
      lfi:               { enabled: step3.lfi },
      rfi:               { enabled: step3.rfi },
      cmd_injection:     { enabled: step3.commandInjection },
      login_attempt:     { enabled: step3.credentialLogging },
      path_traversal:    { enabled: step3.directoryTraversal },
      payload_capture:   { enabled: step3.payloadCapture },
      useragent_capture: { enabled: step3.userAgentCapture },
      cookie_capture:    { enabled: step3.cookieCapture },
      header_capture:    { enabled: step3.headerCapture },
    },
    output: {
      opensearch: { enabled: step4.opensearch.enabled, host: step4.opensearch.host, port: step4.opensearch.port },
      splunk:     { enabled: step4.splunk.enabled,     hec_url: step4.splunk.hecUrl, token: step4.splunk.token ? '***' : '' },
      sentinel:   { enabled: step4.sentinel.enabled,   workspace_id: step4.sentinel.workspaceId, shared_key: step4.sentinel.sharedKey ? '***' : '' },
      qradar:     { enabled: step4.qradar.enabled,     host: step4.qradar.host, port: step4.qradar.port },
      misp:       { enabled: step4.misp.enabled,       url: step4.misp.url, api_key: step4.misp.apiKey ? '***' : '' },
      slack:      { enabled: step4.slack.enabled,      webhook_url: step4.slack.webhookUrl ? '***' : '' },
      email:      { enabled: step4.email.enabled,      address: step4.email.address },
      webhook:    { enabled: step4.webhook.enabled,    url: step4.webhook.url },
    },
  }
  return JSON.stringify(obj, null, 2)
}

/* ──────────────────────────── CodeBlock ──────────────────────────── */

function CodeBlock({ code, lang }: { code: string; lang: string }) {
  const [copied, setCopied] = useState(false)
  const handleCopy = () => {
    navigator.clipboard.writeText(code).then(() => {
      setCopied(true)
      setTimeout(() => setCopied(false), 2000)
    })
  }
  return (
    <div className="rounded-xl border border-hf-border/40 overflow-hidden">
      <div className="flex items-center justify-between px-4 py-2 bg-hf-surface-3 border-b border-hf-border/40">
        <span className="text-[10px] font-mono font-semibold text-hf-dim">{lang}</span>
        <button onClick={handleCopy} className="flex items-center gap-1.5 text-[10px] text-hf-muted hover:text-hf-text transition-colors">
          {copied ? <CheckCheck className="w-3 h-3 text-hf-success" /> : <Copy className="w-3 h-3" />}
          {copied ? 'Copied!' : 'Copy'}
        </button>
      </div>
      <pre className="p-4 overflow-x-auto text-[11px] font-mono text-hf-muted leading-relaxed bg-hf-bg-2 max-h-72">
        <code>{code}</code>
      </pre>
    </div>
  )
}

/* ──────────────────────── Architecture Diagram ──────────────────────── */

function ArchDiagram({ data }: { data: WizardData }) {
  const enabledOutputs = (Object.entries(data.step4) as [string, { enabled: boolean }][])
    .filter(([, v]) => v.enabled)
    .map(([k]) => ({
      opensearch: 'OpenSearch', splunk: 'Splunk', sentinel: 'Sentinel',
      qradar: 'QRadar', misp: 'MISP', slack: 'Slack', email: 'Email', webhook: 'Webhook',
    }[k] ?? k))

  const enabledDetections = (Object.entries(data.step3) as [string, boolean][])
    .filter(([, v]) => v)
    .map(([k]) => ({
      sqlInjection: 'SQLi', xss: 'XSS', lfi: 'LFI', rfi: 'RFI',
      commandInjection: 'CMDi', credentialLogging: 'Creds', directoryTraversal: 'Traversal',
      payloadCapture: 'Payload', userAgentCapture: 'UA', cookieCapture: 'Cookie', headerCapture: 'Headers',
    }[k] ?? k))

  const decoyName = data.step2.name || 'Decoy'

  return (
    <div className="rounded-2xl border border-hf-border/40 bg-hf-bg-2 p-5 overflow-x-auto">
      <p className="text-[10px] font-bold text-hf-dim uppercase tracking-widest mb-4">Architecture Flow</p>
      <div className="flex items-start gap-3 min-w-[560px]">
        {/* Attacker */}
        <div className="flex flex-col items-center gap-1.5">
          <div className="w-20 h-16 rounded-xl border border-hf-danger/40 bg-hf-danger/10 flex flex-col items-center justify-center gap-0.5">
            <span className="text-lg">👤</span>
            <span className="text-[9px] font-bold text-hf-danger">Attacker</span>
          </div>
          <span className="text-[8px] text-hf-dim">Threat Actor</span>
        </div>

        {/* Arrow 1 */}
        <div className="flex flex-col items-center justify-center h-16 pt-1">
          <div className="flex items-center gap-1">
            <div className="w-6 h-px bg-hf-border-2" />
            <ArrowRight className="w-3 h-3 text-hf-border-2" />
          </div>
          <span className="text-[8px] text-hf-dim mt-1">HTTP</span>
        </div>

        {/* SNARE */}
        <div className="flex flex-col items-center gap-1.5">
          <div className="w-20 h-16 rounded-xl border border-hf-primary/50 bg-hf-primary/10 flex flex-col items-center justify-center gap-0.5">
            <span className="text-lg">🕸️</span>
            <span className="text-[9px] font-bold text-hf-primary">SNARE</span>
            <span className="text-[8px] text-hf-dim">:8080</span>
          </div>
          <span className="text-[8px] text-hf-dim">{decoyName}</span>
        </div>

        {/* Arrow 2 */}
        <div className="flex flex-col items-center justify-center h-16 pt-1">
          <div className="flex items-center gap-1">
            <div className="w-6 h-px bg-hf-border-2" />
            <ArrowRight className="w-3 h-3 text-hf-border-2" />
          </div>
          <span className="text-[8px] text-hf-dim mt-1">Events</span>
        </div>

        {/* TANNER */}
        <div className="flex flex-col items-center gap-1.5">
          <div className="w-24 rounded-xl border border-hf-accent/50 bg-hf-accent/10 p-2">
            <div className="text-center">
              <span className="text-base">🎯</span>
              <p className="text-[9px] font-bold text-hf-accent mt-0.5">TANNER</p>
              <p className="text-[8px] text-hf-dim">:8090</p>
            </div>
            {enabledDetections.length > 0 && (
              <div className="flex flex-wrap gap-0.5 mt-2 justify-center">
                {enabledDetections.slice(0, 6).map((d) => (
                  <span key={d} className="text-[7px] text-hf-accent bg-hf-accent/10 border border-hf-accent/20 px-1 py-0.5 rounded">
                    {d}
                  </span>
                ))}
              </div>
            )}
          </div>
          <span className="text-[8px] text-hf-dim">Analysis Engine</span>
        </div>

        {/* Arrow 3 */}
        {enabledOutputs.length > 0 && (
          <>
            <div className="flex flex-col items-center justify-center h-16 pt-1">
              <div className="flex items-center gap-1">
                <div className="w-6 h-px bg-hf-border-2" />
                <ArrowRight className="w-3 h-3 text-hf-border-2" />
              </div>
              <span className="text-[8px] text-hf-dim mt-1">Forward</span>
            </div>

            {/* Outputs */}
            <div className="flex flex-col gap-1.5">
              {enabledOutputs.map((out) => (
                <div
                  key={out}
                  className="h-7 px-2.5 rounded-lg border border-hf-success/30 bg-hf-success/10 flex items-center"
                >
                  <span className="text-[9px] font-semibold text-hf-success">{out}</span>
                </div>
              ))}
            </div>
          </>
        )}
      </div>
    </div>
  )
}

/* ─────────────────────────── Summary Row ────────────────────────────── */

function SummaryRow({ label, value, accent = false }: { label: string; value: string; accent?: boolean }) {
  return (
    <div className="flex items-center gap-3 py-2 border-b border-hf-border/20 last:border-0">
      <span className="text-[11px] text-hf-dim w-36 shrink-0">{label}</span>
      <span className={cn('text-xs font-medium truncate', accent ? 'text-hf-primary' : 'text-hf-text')}>
        {value || <span className="text-hf-dim italic">Not set</span>}
      </span>
    </div>
  )
}

/* ─────────────────────────── Collapsible Section ─────────────────────── */

function Section({ title, badge, children }: { title: string; badge?: string; children: React.ReactNode }) {
  const [open, setOpen] = useState(true)
  return (
    <div className="glass-card rounded-2xl border border-hf-border/40 overflow-hidden">
      <button
        className="w-full flex items-center justify-between px-4 py-3 hover:bg-hf-surface-2/30 transition-colors"
        onClick={() => setOpen(!open)}
      >
        <div className="flex items-center gap-2">
          <h4 className="text-xs font-bold text-hf-text">{title}</h4>
          {badge && (
            <span className="text-[9px] font-semibold text-hf-muted bg-hf-surface-3 border border-hf-border/40 px-1.5 py-0.5 rounded">
              {badge}
            </span>
          )}
        </div>
        {open ? <ChevronUp className="w-4 h-4 text-hf-dim" /> : <ChevronDown className="w-4 h-4 text-hf-dim" />}
      </button>
      {open && <div className="px-4 pb-4">{children}</div>}
    </div>
  )
}

/* ─────────────────────────── Main Component ─────────────────────────── */

export function StepReview({ data, onDeploy, deploying }: StepReviewProps) {
  const enabledDetections = Object.values(data.step3).filter(Boolean).length
  const enabledIntegrations = (Object.values(data.step4) as { enabled: boolean }[]).filter((v) => v.enabled).length

  const snareYaml  = generateSnareYaml(data)
  const tannerJson = generateTannerJson(data)

  return (
    <div className="space-y-5">

      {/* Config summary */}
      <Section title="Clone Source" badge={data.step1.cloneType}>
        <SummaryRow label="Source URL"     value={data.step1.url}      accent />
        <SummaryRow label="Clone Strategy" value={data.step1.cloneType} />
        <SummaryRow label="Auth Required"  value={data.step1.authRequired ? 'Yes' : 'No'} />
        {data.step1.analyzed && (
          <SummaryRow
            label="Detected"
            value={`${data.step1.detectedPages} pages, ${data.step1.detectedForms} forms, ${data.step1.detectedLinks} links`}
          />
        )}
      </Section>

      <Section title="Decoy Configuration">
        <SummaryRow label="Name"            value={data.step2.name}         accent />
        <SummaryRow label="Category"        value={data.step2.category} />
        <SummaryRow label="Department"      value={data.step2.department} />
        <SummaryRow label="Business Owner"  value={data.step2.businessOwner} />
        {data.step2.tags && <SummaryRow label="Tags" value={data.step2.tags} />}
      </Section>

      <Section title="Attack Monitoring" badge={`${enabledDetections} rules`}>
        <div className="flex flex-wrap gap-1.5 pt-1">
          {(Object.entries(data.step3) as [string, boolean][]).map(([key, enabled]) => {
            const label: Record<string, string> = {
              sqlInjection: 'SQLi', xss: 'XSS', lfi: 'LFI', rfi: 'RFI',
              commandInjection: 'CMDi', credentialLogging: 'Credentials',
              directoryTraversal: 'Dir Traversal', payloadCapture: 'Payloads',
              userAgentCapture: 'User-Agent', cookieCapture: 'Cookies', headerCapture: 'Headers',
            }
            return (
              <span
                key={key}
                className={cn(
                  'text-[10px] font-medium px-2 py-0.5 rounded border',
                  enabled
                    ? 'text-hf-success bg-hf-success/10 border-hf-success/30'
                    : 'text-hf-dim bg-hf-surface-3 border-hf-border/30 line-through'
                )}
              >
                {label[key] ?? key}
              </span>
            )
          })}
        </div>
      </Section>

      <Section title="Integrations" badge={`${enabledIntegrations} enabled`}>
        <div className="flex flex-wrap gap-1.5 pt-1">
          {(Object.entries(data.step4) as [string, { enabled: boolean }][]).map(([key, val]) => {
            const label: Record<string, string> = {
              opensearch: 'OpenSearch', splunk: 'Splunk', sentinel: 'Sentinel', qradar: 'QRadar',
              misp: 'MISP', slack: 'Slack', email: 'Email', webhook: 'Webhook',
            }
            return (
              <span
                key={key}
                className={cn(
                  'text-[10px] font-medium px-2 py-0.5 rounded border',
                  val.enabled
                    ? 'text-hf-primary bg-hf-primary/10 border-hf-primary/30'
                    : 'text-hf-dim bg-hf-surface-3 border-hf-border/30'
                )}
              >
                {label[key] ?? key}
              </span>
            )
          })}
        </div>
      </Section>

      {/* Architecture */}
      <div>
        <p className="text-[10px] font-bold text-hf-dim uppercase tracking-widest mb-2 px-1">Deployment Architecture</p>
        <ArchDiagram data={data} />
      </div>

      {/* SNARE config */}
      <div>
        <p className="text-[10px] font-bold text-hf-dim uppercase tracking-widest mb-2 px-1">Generated SNARE Config (YAML)</p>
        <CodeBlock code={snareYaml} lang="snare.yaml" />
      </div>

      {/* TANNER config */}
      <div>
        <p className="text-[10px] font-bold text-hf-dim uppercase tracking-widest mb-2 px-1">Generated TANNER Config (JSON)</p>
        <CodeBlock code={tannerJson} lang="tanner.json" />
      </div>

      {/* Deploy */}
      <div className="flex justify-end pt-2">
        <Button
          variant="primary"
          size="lg"
          isLoading={deploying}
          disabled={!data.step2.name || !data.step1.url}
          onClick={onDeploy}
          leftIcon={<Rocket className="w-4 h-4" />}
        >
          {deploying ? 'Deploying…' : 'Deploy Decoy'}
        </Button>
      </div>

      {(!data.step2.name || !data.step1.url) && (
        <p className="text-xs text-hf-warning text-right -mt-2">
          Complete Step 1 (URL) and Step 2 (Name) before deploying.
        </p>
      )}
    </div>
  )
}
