import type { AuditLog } from '@/types/audit'

// Generated by scripts/gen-audit.js — 102 entries across 7 days
export const MOCK_AUDIT_LOGS: AuditLog[] = [
  {
    "id": "al_0001",
    "userId": "usr_admin_001",
    "userEmail": "admin@honeyforge.io",
    "userRole": "admin",
    "ipAddress": "10.0.0.5",
    "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) Chrome/124.0.0.0 Safari/537.36",
    "timestamp": "2026-06-18T08:30:12Z",
    "sessionId": "sess_a001",
    "action": "login",
    "resourceType": "session",
    "outcome": "success",
    "riskLevel": "low",
    "details": {
      "mfa": true,
      "method": "totp"
    }
  },
  {
    "id": "al_0002",
    "userId": "usr_analyst_002",
    "userEmail": "jsmith@honeyforge.io",
    "userRole": "analyst",
    "ipAddress": "10.0.0.8",
    "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) Firefox/125.0",
    "timestamp": "2026-06-18T08:31:40Z",
    "sessionId": "sess_a002",
    "action": "login",
    "resourceType": "session",
    "outcome": "success",
    "riskLevel": "low",
    "details": {
      "mfa": true,
      "method": "totp"
    }
  },
  {
    "id": "al_0003",
    "userId": "usr_analyst_003",
    "userEmail": "mlee@honeyforge.io",
    "userRole": "analyst",
    "ipAddress": "10.0.0.12",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 14_5) Chrome/124.0.0.0 Safari/537.36",
    "timestamp": "2026-06-18T08:33:05Z",
    "sessionId": "sess_a003",
    "action": "login",
    "resourceType": "session",
    "outcome": "success",
    "riskLevel": "low",
    "details": {
      "mfa": true,
      "method": "totp"
    }
  },
  {
    "id": "al_0004",
    "userId": "usr_analyst_001",
    "userEmail": "analyst@honeyforge.io",
    "userRole": "analyst",
    "ipAddress": "10.0.0.15",
    "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) Edge/124.0.0.0",
    "timestamp": "2026-06-18T08:34:22Z",
    "sessionId": "sess_a004",
    "action": "login",
    "resourceType": "session",
    "outcome": "success",
    "riskLevel": "low",
    "details": {
      "mfa": true,
      "method": "totp"
    }
  },
  {
    "id": "al_0005",
    "userId": "usr_viewer_001",
    "userEmail": "viewer@honeyforge.io",
    "userRole": "viewer",
    "ipAddress": "10.0.0.20",
    "userAgent": "Mozilla/5.0 (X11; Linux x86_64) Chrome/124.0.0.0 Safari/537.36",
    "timestamp": "2026-06-18T08:35:01Z",
    "sessionId": "sess_a005",
    "action": "login",
    "resourceType": "session",
    "outcome": "success",
    "riskLevel": "low",
    "details": {
      "mfa": false,
      "method": "password"
    }
  },
  {
    "id": "al_0006",
    "userId": "usr_admin_001",
    "userEmail": "admin@honeyforge.io",
    "userRole": "admin",
    "ipAddress": "203.0.113.45",
    "userAgent": "Python-urllib/3.11",
    "timestamp": "2026-06-18T08:41:00Z",
    "action": "login",
    "resourceType": "session",
    "outcome": "failed",
    "riskLevel": "critical",
    "details": {
      "reason": "Invalid MFA token",
      "attempts": 3
    }
  },
  {
    "id": "al_0007",
    "userId": "usr_admin_001",
    "userEmail": "admin@honeyforge.io",
    "userRole": "admin",
    "ipAddress": "203.0.113.45",
    "userAgent": "Python-urllib/3.11",
    "timestamp": "2026-06-18T08:41:44Z",
    "action": "login",
    "resourceType": "session",
    "outcome": "failed",
    "riskLevel": "critical",
    "details": {
      "reason": "Invalid MFA token",
      "attempts": 4
    }
  },
  {
    "id": "al_0008",
    "userId": "usr_admin_001",
    "userEmail": "admin@honeyforge.io",
    "userRole": "admin",
    "ipAddress": "185.220.101.38",
    "userAgent": "Python-urllib/3.11",
    "timestamp": "2026-06-18T08:42:07Z",
    "action": "login",
    "resourceType": "session",
    "outcome": "failed",
    "riskLevel": "critical",
    "details": {
      "reason": "Account locked after 5 attempts"
    }
  },
  {
    "id": "al_0009",
    "userId": "usr_analyst_003",
    "userEmail": "mlee@honeyforge.io",
    "userRole": "analyst",
    "ipAddress": "10.0.0.12",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 14_5) Chrome/124.0.0.0 Safari/537.36",
    "timestamp": "2026-06-18T09:02:14Z",
    "resourceId": "evt_8821",
    "resourceName": "Mass SSH Scanning — 103.27.202.187",
    "action": "event_marked_attack",
    "resourceType": "event",
    "outcome": "success",
    "riskLevel": "low",
    "details": {
      "confidence": "high",
      "mitre": "T1046",
      "iocs": [
        "103.27.202.187"
      ]
    }
  },
  {
    "id": "al_0010",
    "userId": "usr_analyst_002",
    "userEmail": "jsmith@honeyforge.io",
    "userRole": "analyst",
    "ipAddress": "10.0.0.8",
    "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) Firefox/125.0",
    "timestamp": "2026-06-18T09:08:33Z",
    "resourceId": "evt_8822",
    "resourceName": "Cobalt Strike Beacon — 91.219.237.41",
    "action": "event_marked_attack",
    "resourceType": "event",
    "outcome": "success",
    "riskLevel": "low",
    "details": {
      "confidence": "critical",
      "mitre": "T1071.001",
      "iocs": [
        "91.219.237.41",
        "185.220.101.22"
      ]
    }
  },
  {
    "id": "al_0011",
    "userId": "usr_analyst_001",
    "userEmail": "analyst@honeyforge.io",
    "userRole": "analyst",
    "ipAddress": "10.0.0.15",
    "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) Edge/124.0.0.0",
    "timestamp": "2026-06-18T09:15:47Z",
    "resourceId": "evt_8819",
    "resourceName": "Internal Port Scan — 10.0.0.88",
    "action": "event_marked_benign",
    "resourceType": "event",
    "outcome": "success",
    "riskLevel": "low",
    "details": {
      "reason": "Authorized vulnerability scanner",
      "scanner": "Nessus"
    }
  },
  {
    "id": "al_0012",
    "userId": "usr_analyst_003",
    "userEmail": "mlee@honeyforge.io",
    "userRole": "analyst",
    "ipAddress": "10.0.0.12",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 14_5) Chrome/124.0.0.0 Safari/537.36",
    "timestamp": "2026-06-18T09:22:55Z",
    "action": "ioc_exported",
    "resourceType": "ioc",
    "outcome": "success",
    "riskLevel": "medium",
    "details": {
      "count": 12,
      "format": "STIX 2.1",
      "destination": "MISP",
      "tlp": "AMBER"
    }
  },
  {
    "id": "al_0013",
    "userId": "usr_admin_001",
    "userEmail": "admin@honeyforge.io",
    "userRole": "admin",
    "ipAddress": "10.0.0.5",
    "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) Chrome/124.0.0.0 Safari/537.36",
    "timestamp": "2026-06-18T09:31:18Z",
    "resourceId": "int_opensearch",
    "resourceName": "OpenSearch SIEM",
    "action": "integration_configured",
    "resourceType": "integration",
    "outcome": "success",
    "riskLevel": "high",
    "details": {
      "changes": [
        "index_name: hf-events-v2 → hf-events-v3",
        "flush_interval: 5s → 10s"
      ]
    }
  },
  {
    "id": "al_0014",
    "userId": "usr_analyst_002",
    "userEmail": "jsmith@honeyforge.io",
    "userRole": "analyst",
    "ipAddress": "10.0.0.8",
    "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) Firefox/125.0",
    "timestamp": "2026-06-18T09:47:03Z",
    "resourceId": "r_001",
    "resourceName": "SSH Brute Force Detection",
    "action": "rule_enabled",
    "resourceType": "rule",
    "outcome": "success",
    "riskLevel": "medium",
    "details": {
      "previousStatus": "disabled",
      "triggeredBy": "threat campaign"
    }
  },
  {
    "id": "al_0015",
    "userId": "usr_admin_001",
    "userEmail": "admin@honeyforge.io",
    "userRole": "admin",
    "ipAddress": "10.0.0.5",
    "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) Chrome/124.0.0.0 Safari/537.36",
    "timestamp": "2026-06-18T10:02:44Z",
    "resourceId": "d_012",
    "resourceName": "Cowrie-SSH-SG-04",
    "action": "decoy_created",
    "resourceType": "decoy",
    "outcome": "success",
    "riskLevel": "medium",
    "details": {
      "type": "ssh",
      "port": 22,
      "region": "ap-southeast-1",
      "template": "ubuntu-22.04-cowrie"
    }
  },
  {
    "id": "al_0016",
    "userId": "usr_analyst_003",
    "userEmail": "mlee@honeyforge.io",
    "userRole": "analyst",
    "ipAddress": "10.0.0.12",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 14_5) Chrome/124.0.0.0 Safari/537.36",
    "timestamp": "2026-06-18T10:31:22Z",
    "resourceId": "rep_daily",
    "resourceName": "Daily Honeypot Summary",
    "action": "report_generated",
    "resourceType": "report",
    "outcome": "success",
    "riskLevel": "low",
    "details": {
      "format": "pdf",
      "fileSize": 1248921,
      "recipients": 2
    }
  },
  {
    "id": "al_0017",
    "userId": "usr_analyst_002",
    "userEmail": "jsmith@honeyforge.io",
    "userRole": "analyst",
    "ipAddress": "10.0.0.8",
    "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) Firefox/125.0",
    "timestamp": "2026-06-18T11:04:09Z",
    "resourceId": "evt_8825",
    "resourceName": "XMRig Cryptominer Download via SSH",
    "action": "event_marked_attack",
    "resourceType": "event",
    "outcome": "success",
    "riskLevel": "low",
    "details": {
      "confidence": "high",
      "mitre": "T1496",
      "sha256": "e3b0c44298fc1c149afbf4c8996fb924"
    }
  },
  {
    "id": "al_0018",
    "userId": "usr_admin_001",
    "userEmail": "admin@honeyforge.io",
    "userRole": "admin",
    "ipAddress": "10.0.0.5",
    "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) Chrome/124.0.0.0 Safari/537.36",
    "timestamp": "2026-06-18T11:17:34Z",
    "action": "settings_changed",
    "resourceType": "settings",
    "outcome": "success",
    "riskLevel": "high",
    "details": {
      "key": "alert_threshold",
      "from": "medium",
      "to": "high",
      "reason": "Active threat campaign"
    }
  },
  {
    "id": "al_0019",
    "userId": "usr_viewer_001",
    "userEmail": "viewer@honeyforge.io",
    "userRole": "viewer",
    "ipAddress": "10.0.0.20",
    "userAgent": "Mozilla/5.0 (X11; Linux x86_64) Chrome/124.0.0.0 Safari/537.36",
    "timestamp": "2026-06-18T11:30:00Z",
    "resourceId": "r_005",
    "resourceName": "HTTP Path Traversal",
    "action": "rule_disabled",
    "resourceType": "rule",
    "outcome": "failed",
    "riskLevel": "medium",
    "details": {
      "reason": "Insufficient permissions — viewer role cannot modify rules"
    }
  },
  {
    "id": "al_0020",
    "userId": "usr_admin_001",
    "userEmail": "admin@honeyforge.io",
    "userRole": "admin",
    "ipAddress": "10.0.0.5",
    "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) Chrome/124.0.0.0 Safari/537.36",
    "timestamp": "2026-06-18T12:03:55Z",
    "sessionId": "sess_a006",
    "action": "login",
    "resourceType": "session",
    "outcome": "warning",
    "riskLevel": "medium",
    "details": {
      "warning": "New device fingerprint detected",
      "mfa": true,
      "method": "totp"
    }
  },
  {
    "id": "al_0021",
    "userId": "usr_analyst_001",
    "userEmail": "analyst@honeyforge.io",
    "userRole": "analyst",
    "ipAddress": "10.0.0.15",
    "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) Edge/124.0.0.0",
    "timestamp": "2026-06-18T12:45:18Z",
    "resourceId": "evt_8830",
    "resourceName": "MySQL Auth Probe — 37.44.238.92",
    "action": "event_marked_attack",
    "resourceType": "event",
    "outcome": "success",
    "riskLevel": "low",
    "details": {
      "confidence": "medium",
      "mitre": "T1110",
      "port": 3306
    }
  },
  {
    "id": "al_0022",
    "userId": "usr_analyst_003",
    "userEmail": "mlee@honeyforge.io",
    "userRole": "analyst",
    "ipAddress": "10.0.0.12",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 14_5) Chrome/124.0.0.0 Safari/537.36",
    "timestamp": "2026-06-18T13:02:00Z",
    "action": "ioc_exported",
    "resourceType": "ioc",
    "outcome": "success",
    "riskLevel": "medium",
    "details": {
      "count": 7,
      "format": "CSV",
      "destination": "Threat Intel Platform",
      "tlp": "WHITE"
    }
  },
  {
    "id": "al_0023",
    "userId": "usr_analyst_002",
    "userEmail": "jsmith@honeyforge.io",
    "userRole": "analyst",
    "ipAddress": "10.0.0.8",
    "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) Firefox/125.0",
    "timestamp": "2026-06-18T13:20:42Z",
    "action": "clone_studio_changed",
    "resourceType": "clone-studio",
    "outcome": "success",
    "riskLevel": "medium",
    "details": {
      "changes": [
        "fingerprint: generic-nginx → CVE-2023-44487-patched",
        "banner_version: 1.18.0 → 1.25.3"
      ]
    }
  },
  {
    "id": "al_0024",
    "userId": "usr_admin_001",
    "userEmail": "admin@honeyforge.io",
    "userRole": "admin",
    "ipAddress": "10.0.0.5",
    "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) Chrome/124.0.0.0 Safari/537.36",
    "timestamp": "2026-06-18T14:00:07Z",
    "resourceId": "r_021",
    "resourceName": "Log4Shell RCE Attempt (CVE-2021-44228)",
    "action": "rule_created",
    "resourceType": "rule",
    "outcome": "success",
    "riskLevel": "medium",
    "details": {
      "type": "sigma",
      "severity": "critical",
      "mitre": "T1190"
    }
  },
  {
    "id": "al_0025",
    "userId": "usr_analyst_003",
    "userEmail": "mlee@honeyforge.io",
    "userRole": "analyst",
    "ipAddress": "10.0.0.12",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 14_5) Chrome/124.0.0.0 Safari/537.36",
    "timestamp": "2026-06-18T14:33:29Z",
    "resourceId": "evt_8828",
    "resourceName": "Internal ICMP Sweep — 10.0.0.0/24",
    "action": "event_marked_benign",
    "resourceType": "event",
    "outcome": "success",
    "riskLevel": "low",
    "details": {
      "reason": "Scheduled network health check",
      "approvedBy": "admin@honeyforge.io"
    }
  },
  {
    "id": "al_0026",
    "userId": "usr_analyst_001",
    "userEmail": "analyst@honeyforge.io",
    "userRole": "analyst",
    "ipAddress": "10.0.0.15",
    "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) Edge/124.0.0.0",
    "timestamp": "2026-06-17T07:01:00Z",
    "sessionId": "sess_b001",
    "action": "login",
    "resourceType": "session",
    "outcome": "success",
    "riskLevel": "low",
    "details": {
      "mfa": true,
      "method": "totp"
    }
  },
  {
    "id": "al_0027",
    "userId": "usr_analyst_002",
    "userEmail": "jsmith@honeyforge.io",
    "userRole": "analyst",
    "ipAddress": "10.0.0.8",
    "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) Firefox/125.0",
    "timestamp": "2026-06-17T07:04:30Z",
    "sessionId": "sess_b002",
    "action": "login",
    "resourceType": "session",
    "outcome": "success",
    "riskLevel": "low",
    "details": {
      "mfa": true,
      "method": "totp"
    }
  },
  {
    "id": "al_0028",
    "userId": "usr_analyst_003",
    "userEmail": "mlee@honeyforge.io",
    "userRole": "analyst",
    "ipAddress": "10.0.0.12",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 14_5) Chrome/124.0.0.0 Safari/537.36",
    "timestamp": "2026-06-17T07:08:00Z",
    "sessionId": "sess_b003",
    "action": "login",
    "resourceType": "session",
    "outcome": "success",
    "riskLevel": "low",
    "details": {
      "mfa": true,
      "method": "totp"
    }
  },
  {
    "id": "al_0029",
    "userId": "usr_analyst_003",
    "userEmail": "mlee@honeyforge.io",
    "userRole": "analyst",
    "ipAddress": "10.0.0.12",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 14_5) Chrome/124.0.0.0 Safari/537.36",
    "timestamp": "2026-06-17T07:30:14Z",
    "resourceId": "evt_8810",
    "resourceName": "Tor Exit Node Probe — 185.220.101.50",
    "action": "event_marked_attack",
    "resourceType": "event",
    "outcome": "success",
    "riskLevel": "low",
    "details": {
      "confidence": "high",
      "mitre": "T1090.003",
      "iocs": [
        "185.220.101.50"
      ]
    }
  },
  {
    "id": "al_0030",
    "userId": "usr_analyst_003",
    "userEmail": "mlee@honeyforge.io",
    "userRole": "analyst",
    "ipAddress": "10.0.0.12",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 14_5) Chrome/124.0.0.0 Safari/537.36",
    "timestamp": "2026-06-17T07:44:52Z",
    "resourceId": "evt_8812",
    "resourceName": "Telnet Default Credential Attempt",
    "action": "event_marked_attack",
    "resourceType": "event",
    "outcome": "success",
    "riskLevel": "low",
    "details": {
      "confidence": "high",
      "credential": "admin:admin",
      "mitre": "T1078"
    }
  },
  {
    "id": "al_0031",
    "userId": "usr_analyst_001",
    "userEmail": "analyst@honeyforge.io",
    "userRole": "analyst",
    "ipAddress": "10.0.0.15",
    "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) Edge/124.0.0.0",
    "timestamp": "2026-06-17T08:02:10Z",
    "action": "ioc_exported",
    "resourceType": "ioc",
    "outcome": "success",
    "riskLevel": "medium",
    "details": {
      "count": 23,
      "format": "STIX 2.1",
      "destination": "ISAC Feed",
      "tlp": "GREEN"
    }
  },
  {
    "id": "al_0032",
    "userId": "usr_analyst_002",
    "userEmail": "jsmith@honeyforge.io",
    "userRole": "analyst",
    "ipAddress": "10.0.0.8",
    "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) Firefox/125.0",
    "timestamp": "2026-06-17T09:00:38Z",
    "resourceId": "r_020",
    "resourceName": "DNS Tunneling via Base64 Encoding",
    "action": "rule_created",
    "resourceType": "rule",
    "outcome": "success",
    "riskLevel": "medium",
    "details": {
      "type": "sigma",
      "severity": "high",
      "mitre": "T1071.004"
    }
  },
  {
    "id": "al_0033",
    "userId": "usr_admin_001",
    "userEmail": "admin@honeyforge.io",
    "userRole": "admin",
    "ipAddress": "10.0.0.5",
    "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) Chrome/124.0.0.0 Safari/537.36",
    "timestamp": "2026-06-17T09:29:00Z",
    "resourceId": "int_slack",
    "resourceName": "Slack Alerting",
    "action": "integration_configured",
    "resourceType": "integration",
    "outcome": "success",
    "riskLevel": "high",
    "details": {
      "changes": [
        "channel: #soc → #soc-critical",
        "mention_on_critical: false → true"
      ]
    }
  },
  {
    "id": "al_0034",
    "userId": "usr_analyst_003",
    "userEmail": "mlee@honeyforge.io",
    "userRole": "analyst",
    "ipAddress": "10.0.0.12",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 14_5) Chrome/124.0.0.0 Safari/537.36",
    "timestamp": "2026-06-17T10:00:00Z",
    "resourceId": "evt_8808",
    "resourceName": "DevOps CI Runner — 10.0.0.99",
    "action": "event_marked_benign",
    "resourceType": "event",
    "outcome": "success",
    "riskLevel": "low",
    "details": {
      "reason": "Known build pipeline, confirmed with DevOps team"
    }
  },
  {
    "id": "al_0035",
    "userId": "usr_analyst_001",
    "userEmail": "analyst@honeyforge.io",
    "userRole": "analyst",
    "ipAddress": "10.0.0.15",
    "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) Edge/124.0.0.0",
    "timestamp": "2026-06-17T11:02:44Z",
    "resourceId": "rep_ssh",
    "resourceName": "SSH Brute Force Report",
    "action": "report_generated",
    "resourceType": "report",
    "outcome": "success",
    "riskLevel": "low",
    "details": {
      "format": "pdf",
      "fileSize": 892334,
      "period": "7d"
    }
  },
  {
    "id": "al_0036",
    "userId": "usr_admin_001",
    "userEmail": "admin@honeyforge.io",
    "userRole": "admin",
    "ipAddress": "10.0.0.5",
    "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) Chrome/124.0.0.0 Safari/537.36",
    "timestamp": "2026-06-17T12:00:00Z",
    "resourceId": "d_008",
    "resourceName": "SNARE-HTTP-02",
    "action": "decoy_paused",
    "resourceType": "decoy",
    "outcome": "success",
    "riskLevel": "medium",
    "details": {
      "reason": "Scheduled maintenance window",
      "resumeAt": "2026-06-17T14:00:00Z"
    }
  },
  {
    "id": "al_0037",
    "userId": "usr_analyst_002",
    "userEmail": "jsmith@honeyforge.io",
    "userRole": "analyst",
    "ipAddress": "10.0.0.8",
    "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) Firefox/125.0",
    "timestamp": "2026-06-17T14:11:22Z",
    "resourceId": "thr_441",
    "resourceName": "APT41 Campaign IOC Cluster",
    "action": "threat_assigned",
    "resourceType": "threat",
    "outcome": "success",
    "riskLevel": "low",
    "details": {
      "assignedTo": "mlee@honeyforge.io",
      "priority": "high"
    }
  },
  {
    "id": "al_0038",
    "userId": "usr_analyst_003",
    "userEmail": "mlee@honeyforge.io",
    "userRole": "analyst",
    "ipAddress": "10.0.0.12",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 14_5) Chrome/124.0.0.0 Safari/537.36",
    "timestamp": "2026-06-17T15:05:18Z",
    "resourceId": "thr_439",
    "resourceName": "FIN7 Phishing Pivot Attempt",
    "action": "threat_resolved",
    "resourceType": "threat",
    "outcome": "success",
    "riskLevel": "low",
    "details": {
      "resolution": "Contained — decoy interactions catalogued, no lateral movement",
      "ttc": "4h 22m"
    }
  },
  {
    "id": "al_0039",
    "userId": "usr_admin_001",
    "userEmail": "admin@honeyforge.io",
    "userRole": "admin",
    "ipAddress": "10.0.0.5",
    "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) Chrome/124.0.0.0 Safari/537.36",
    "timestamp": "2026-06-17T16:00:55Z",
    "resourceId": "usr_viewer_001",
    "resourceName": "viewer@honeyforge.io",
    "action": "role_changed",
    "resourceType": "user",
    "outcome": "success",
    "riskLevel": "critical",
    "details": {
      "from": "viewer",
      "to": "analyst",
      "reason": "Analyst onboarding complete, probation lifted"
    }
  },
  {
    "id": "al_0040",
    "userId": "usr_admin_001",
    "userEmail": "admin@honeyforge.io",
    "userRole": "admin",
    "ipAddress": "10.0.0.5",
    "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) Chrome/124.0.0.0 Safari/537.36",
    "timestamp": "2026-06-17T16:30:00Z",
    "action": "settings_changed",
    "resourceType": "settings",
    "outcome": "success",
    "riskLevel": "high",
    "details": {
      "key": "session_timeout_minutes",
      "from": 480,
      "to": 240,
      "reason": "Security policy update"
    }
  },
  {
    "id": "al_0041",
    "userId": "usr_admin_001",
    "userEmail": "admin@honeyforge.io",
    "userRole": "admin",
    "ipAddress": "10.0.0.5",
    "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) Chrome/124.0.0.0 Safari/537.36",
    "timestamp": "2026-06-17T17:02:00Z",
    "sessionId": "sess_b010",
    "action": "logout",
    "resourceType": "session",
    "outcome": "success",
    "riskLevel": "low",
    "details": {
      "duration": "9h 32m"
    }
  },
  {
    "id": "al_0042",
    "userId": "usr_analyst_002",
    "userEmail": "jsmith@honeyforge.io",
    "userRole": "analyst",
    "ipAddress": "10.0.0.8",
    "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) Firefox/125.0",
    "timestamp": "2026-06-17T17:30:44Z",
    "sessionId": "sess_b002",
    "action": "logout",
    "resourceType": "session",
    "outcome": "success",
    "riskLevel": "low",
    "details": {
      "duration": "10h 26m"
    }
  },
  {
    "id": "al_0043",
    "userId": "usr_admin_001",
    "userEmail": "admin@honeyforge.io",
    "userRole": "admin",
    "ipAddress": "10.0.0.5",
    "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) Chrome/124.0.0.0 Safari/537.36",
    "timestamp": "2026-06-16T07:00:00Z",
    "sessionId": "sess_c001",
    "action": "login",
    "resourceType": "session",
    "outcome": "success",
    "riskLevel": "low",
    "details": {
      "mfa": true,
      "method": "totp"
    }
  },
  {
    "id": "al_0044",
    "userId": "usr_analyst_002",
    "userEmail": "jsmith@honeyforge.io",
    "userRole": "analyst",
    "ipAddress": "10.0.0.8",
    "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) Firefox/125.0",
    "timestamp": "2026-06-16T07:15:00Z",
    "sessionId": "sess_c002",
    "action": "login",
    "resourceType": "session",
    "outcome": "success",
    "riskLevel": "low",
    "details": {
      "mfa": true,
      "method": "totp"
    }
  },
  {
    "id": "al_0045",
    "userId": "usr_admin_001",
    "userEmail": "admin@honeyforge.io",
    "userRole": "admin",
    "ipAddress": "10.0.0.5",
    "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) Chrome/124.0.0.0 Safari/537.36",
    "timestamp": "2026-06-16T08:00:00Z",
    "resourceId": "usr_analyst_004",
    "resourceName": "priya.v@honeyforge.io",
    "action": "user_created",
    "resourceType": "user",
    "outcome": "success",
    "riskLevel": "high",
    "details": {
      "role": "analyst",
      "mfa_required": true,
      "onboarded_by": "admin@honeyforge.io"
    }
  },
  {
    "id": "al_0046",
    "userId": "usr_analyst_002",
    "userEmail": "jsmith@honeyforge.io",
    "userRole": "analyst",
    "ipAddress": "10.0.0.8",
    "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) Firefox/125.0",
    "timestamp": "2026-06-16T08:15:10Z",
    "resourceId": "r_008",
    "resourceName": "Ransomware File Extension Spike",
    "action": "rule_enabled",
    "resourceType": "rule",
    "outcome": "success",
    "riskLevel": "medium",
    "details": {
      "previousStatus": "draft",
      "approvedBy": "admin@honeyforge.io"
    }
  },
  {
    "id": "al_0047",
    "userId": "usr_analyst_003",
    "userEmail": "mlee@honeyforge.io",
    "userRole": "analyst",
    "ipAddress": "10.0.0.12",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 14_5) Chrome/124.0.0.0 Safari/537.36",
    "timestamp": "2026-06-16T09:00:00Z",
    "sessionId": "sess_c003",
    "action": "login",
    "resourceType": "session",
    "outcome": "success",
    "riskLevel": "low",
    "details": {
      "mfa": true,
      "method": "totp"
    }
  },
  {
    "id": "al_0048",
    "userId": "usr_analyst_002",
    "userEmail": "jsmith@honeyforge.io",
    "userRole": "analyst",
    "ipAddress": "10.0.0.8",
    "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) Firefox/125.0",
    "timestamp": "2026-06-16T09:30:22Z",
    "resourceId": "evt_8790",
    "resourceName": "CVE-2023-44487 HTTP/2 Flood",
    "action": "event_marked_attack",
    "resourceType": "event",
    "outcome": "success",
    "riskLevel": "low",
    "details": {
      "confidence": "critical",
      "mitre": "T1499.004",
      "cve": "CVE-2023-44487"
    }
  },
  {
    "id": "al_0049",
    "userId": "usr_admin_001",
    "userEmail": "admin@honeyforge.io",
    "userRole": "admin",
    "ipAddress": "10.0.0.5",
    "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) Chrome/124.0.0.0 Safari/537.36",
    "timestamp": "2026-06-16T10:00:00Z",
    "resourceId": "int_splunk",
    "resourceName": "Splunk SIEM",
    "action": "integration_configured",
    "resourceType": "integration",
    "outcome": "warning",
    "riskLevel": "high",
    "details": {
      "warning": "TLS certificate expiring in 8 days",
      "changes": [
        "index: main → hf_honeypot"
      ]
    }
  },
  {
    "id": "al_0050",
    "userId": "usr_analyst_003",
    "userEmail": "mlee@honeyforge.io",
    "userRole": "analyst",
    "ipAddress": "10.0.0.12",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 14_5) Chrome/124.0.0.0 Safari/537.36",
    "timestamp": "2026-06-16T10:30:00Z",
    "action": "clone_studio_changed",
    "resourceType": "clone-studio",
    "outcome": "success",
    "riskLevel": "medium",
    "details": {
      "changes": [
        "lure_page: login-portal-v1 → login-portal-v2",
        "enabled_services: [ssh, http] → [ssh, http, ftp]"
      ]
    }
  },
  {
    "id": "al_0051",
    "userId": "usr_analyst_001",
    "userEmail": "analyst@honeyforge.io",
    "userRole": "analyst",
    "ipAddress": "10.0.0.15",
    "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) Edge/124.0.0.0",
    "timestamp": "2026-06-16T11:00:00Z",
    "resourceId": "evt_8785",
    "resourceName": "Heartbeat Check — monitoring.internal",
    "action": "event_marked_benign",
    "resourceType": "event",
    "outcome": "success",
    "riskLevel": "low",
    "details": {
      "reason": "Prometheus scraper, confirmed with SRE team"
    }
  },
  {
    "id": "al_0052",
    "userId": "usr_analyst_002",
    "userEmail": "jsmith@honeyforge.io",
    "userRole": "analyst",
    "ipAddress": "10.0.0.8",
    "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) Firefox/125.0",
    "timestamp": "2026-06-16T11:45:55Z",
    "action": "ioc_exported",
    "resourceType": "ioc",
    "outcome": "success",
    "riskLevel": "medium",
    "details": {
      "count": 18,
      "format": "OpenIOC",
      "destination": "TheHive",
      "tlp": "AMBER"
    }
  },
  {
    "id": "al_0053",
    "userId": "usr_admin_001",
    "userEmail": "admin@honeyforge.io",
    "userRole": "admin",
    "ipAddress": "10.0.0.5",
    "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) Chrome/124.0.0.0 Safari/537.36",
    "timestamp": "2026-06-16T12:00:00Z",
    "resourceId": "d_011",
    "resourceName": "Dionaea-FTP-EU-03",
    "action": "decoy_created",
    "resourceType": "decoy",
    "outcome": "success",
    "riskLevel": "medium",
    "details": {
      "type": "ftp",
      "port": 21,
      "region": "eu-west-2",
      "template": "vsftpd-2.3.4"
    }
  },
  {
    "id": "al_0054",
    "userId": "usr_analyst_003",
    "userEmail": "mlee@honeyforge.io",
    "userRole": "analyst",
    "ipAddress": "10.0.0.12",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 14_5) Chrome/124.0.0.0 Safari/537.36",
    "timestamp": "2026-06-16T14:00:00Z",
    "resourceId": "rep_web",
    "resourceName": "Web Attack Trends Report",
    "action": "report_generated",
    "resourceType": "report",
    "outcome": "success",
    "riskLevel": "low",
    "details": {
      "format": "pdf",
      "fileSize": 1104882
    }
  },
  {
    "id": "al_0055",
    "userId": "usr_analyst_002",
    "userEmail": "jsmith@honeyforge.io",
    "userRole": "analyst",
    "ipAddress": "10.0.0.8",
    "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) Firefox/125.0",
    "timestamp": "2026-06-16T14:55:00Z",
    "resourceId": "r_003",
    "resourceName": "Generic HTTP Scanner Detection",
    "action": "rule_disabled",
    "resourceType": "rule",
    "outcome": "success",
    "riskLevel": "medium",
    "details": {
      "reason": "Too many false positives from internal scanner, being retune",
      "nextReview": "2026-06-23"
    }
  },
  {
    "id": "al_0056",
    "userId": "usr_admin_001",
    "userEmail": "admin@honeyforge.io",
    "userRole": "admin",
    "ipAddress": "10.0.0.5",
    "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) Chrome/124.0.0.0 Safari/537.36",
    "timestamp": "2026-06-16T17:00:00Z",
    "sessionId": "sess_c001",
    "action": "logout",
    "resourceType": "session",
    "outcome": "success",
    "riskLevel": "low",
    "details": {
      "duration": "10h 00m"
    }
  },
  {
    "id": "al_0057",
    "userId": "usr_admin_001",
    "userEmail": "admin@honeyforge.io",
    "userRole": "admin",
    "ipAddress": "10.0.0.5",
    "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) Chrome/124.0.0.0 Safari/537.36",
    "timestamp": "2026-06-15T07:00:00Z",
    "sessionId": "sess_d001",
    "action": "login",
    "resourceType": "session",
    "outcome": "success",
    "riskLevel": "low",
    "details": {
      "mfa": true,
      "method": "totp"
    }
  },
  {
    "id": "al_0058",
    "userId": "usr_admin_001",
    "userEmail": "admin@honeyforge.io",
    "userRole": "admin",
    "ipAddress": "10.0.0.5",
    "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) Chrome/124.0.0.0 Safari/537.36",
    "timestamp": "2026-06-15T08:00:00Z",
    "action": "settings_changed",
    "resourceType": "settings",
    "outcome": "success",
    "riskLevel": "high",
    "details": {
      "key": "data_retention_days",
      "from": 90,
      "to": 180,
      "reason": "Compliance audit requirement"
    }
  },
  {
    "id": "al_0059",
    "userId": "usr_analyst_002",
    "userEmail": "jsmith@honeyforge.io",
    "userRole": "analyst",
    "ipAddress": "10.0.0.8",
    "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) Firefox/125.0",
    "timestamp": "2026-06-15T08:30:00Z",
    "sessionId": "sess_d002",
    "action": "login",
    "resourceType": "session",
    "outcome": "success",
    "riskLevel": "low",
    "details": {
      "mfa": true,
      "method": "totp"
    }
  },
  {
    "id": "al_0060",
    "userId": "usr_analyst_003",
    "userEmail": "mlee@honeyforge.io",
    "userRole": "analyst",
    "ipAddress": "10.0.0.12",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 14_5) Chrome/124.0.0.0 Safari/537.36",
    "timestamp": "2026-06-15T09:00:00Z",
    "sessionId": "sess_d003",
    "action": "login",
    "resourceType": "session",
    "outcome": "success",
    "riskLevel": "low",
    "details": {
      "mfa": true,
      "method": "totp"
    }
  },
  {
    "id": "al_0061",
    "userId": "usr_analyst_001",
    "userEmail": "analyst@honeyforge.io",
    "userRole": "analyst",
    "ipAddress": "10.0.0.15",
    "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) Edge/124.0.0.0",
    "timestamp": "2026-06-15T09:15:00Z",
    "sessionId": "sess_d004",
    "action": "login",
    "resourceType": "session",
    "outcome": "success",
    "riskLevel": "low",
    "details": {
      "mfa": true,
      "method": "totp"
    }
  },
  {
    "id": "al_0062",
    "userId": "usr_analyst_003",
    "userEmail": "mlee@honeyforge.io",
    "userRole": "analyst",
    "ipAddress": "10.0.0.12",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 14_5) Chrome/124.0.0.0 Safari/537.36",
    "timestamp": "2026-06-15T09:30:00Z",
    "resourceId": "evt_8770",
    "resourceName": "BlueKeep Exploit Attempt — 45.155.205.10",
    "action": "event_marked_attack",
    "resourceType": "event",
    "outcome": "success",
    "riskLevel": "low",
    "details": {
      "confidence": "critical",
      "cve": "CVE-2019-0708",
      "mitre": "T1210"
    }
  },
  {
    "id": "al_0063",
    "userId": "usr_admin_001",
    "userEmail": "admin@honeyforge.io",
    "userRole": "admin",
    "ipAddress": "10.0.0.5",
    "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) Chrome/124.0.0.0 Safari/537.36",
    "timestamp": "2026-06-15T10:00:00Z",
    "resourceId": "int_jira",
    "resourceName": "Jira Case Management",
    "action": "integration_configured",
    "resourceType": "integration",
    "outcome": "success",
    "riskLevel": "high",
    "details": {
      "changes": [
        "project_key: SOC → HUNT",
        "auto_create_threshold: high → critical"
      ]
    }
  },
  {
    "id": "al_0064",
    "userId": "usr_analyst_002",
    "userEmail": "jsmith@honeyforge.io",
    "userRole": "analyst",
    "ipAddress": "10.0.0.8",
    "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) Firefox/125.0",
    "timestamp": "2026-06-15T10:30:00Z",
    "resourceId": "r_012",
    "resourceName": "SMB Lateral Movement Probe",
    "action": "rule_updated",
    "resourceType": "rule",
    "outcome": "success",
    "riskLevel": "medium",
    "details": {
      "changes": [
        "threshold: 5 → 3",
        "window: 60s → 30s"
      ],
      "reason": "Reduce dwell time"
    }
  },
  {
    "id": "al_0065",
    "userId": "usr_analyst_003",
    "userEmail": "mlee@honeyforge.io",
    "userRole": "analyst",
    "ipAddress": "10.0.0.12",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 14_5) Chrome/124.0.0.0 Safari/537.36",
    "timestamp": "2026-06-15T11:00:00Z",
    "action": "ioc_exported",
    "resourceType": "ioc",
    "outcome": "success",
    "riskLevel": "medium",
    "details": {
      "count": 35,
      "format": "STIX 2.1",
      "destination": "MISP",
      "tlp": "GREEN"
    }
  },
  {
    "id": "al_0066",
    "userId": "usr_analyst_001",
    "userEmail": "analyst@honeyforge.io",
    "userRole": "analyst",
    "ipAddress": "10.0.0.15",
    "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) Edge/124.0.0.0",
    "timestamp": "2026-06-15T11:30:00Z",
    "resourceId": "evt_8772",
    "resourceName": "Redis Unauthorized SLAVEOF",
    "action": "event_marked_attack",
    "resourceType": "event",
    "outcome": "success",
    "riskLevel": "low",
    "details": {
      "confidence": "high",
      "mitre": "T1219",
      "port": 6379
    }
  },
  {
    "id": "al_0067",
    "userId": "usr_admin_001",
    "userEmail": "admin@honeyforge.io",
    "userRole": "admin",
    "ipAddress": "10.0.0.5",
    "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) Chrome/124.0.0.0 Safari/537.36",
    "timestamp": "2026-06-15T12:00:00Z",
    "resourceId": "d_005",
    "resourceName": "Glastopf-HTTP-01",
    "action": "decoy_paused",
    "resourceType": "decoy",
    "outcome": "success",
    "riskLevel": "medium",
    "details": {
      "reason": "Decommissioning — replacing with Heralding",
      "scheduledDelete": "2026-06-22"
    }
  },
  {
    "id": "al_0068",
    "userId": "usr_analyst_002",
    "userEmail": "jsmith@honeyforge.io",
    "userRole": "analyst",
    "ipAddress": "10.0.0.8",
    "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) Firefox/125.0",
    "timestamp": "2026-06-15T13:00:00Z",
    "resourceId": "thr_440",
    "resourceName": "Lazarus Group RDP Probes",
    "action": "threat_assigned",
    "resourceType": "threat",
    "outcome": "success",
    "riskLevel": "low",
    "details": {
      "assignedTo": "analyst@honeyforge.io",
      "priority": "critical"
    }
  },
  {
    "id": "al_0069",
    "userId": "usr_analyst_003",
    "userEmail": "mlee@honeyforge.io",
    "userRole": "analyst",
    "ipAddress": "10.0.0.12",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 14_5) Chrome/124.0.0.0 Safari/537.36",
    "timestamp": "2026-06-15T14:30:00Z",
    "resourceId": "rep_exec",
    "resourceName": "Monthly Executive Security Report",
    "action": "report_generated",
    "resourceType": "report",
    "outcome": "success",
    "riskLevel": "low",
    "details": {
      "format": "pdf",
      "fileSize": 3248123,
      "period": "30d"
    }
  },
  {
    "id": "al_0070",
    "userId": "usr_analyst_001",
    "userEmail": "analyst@honeyforge.io",
    "userRole": "analyst",
    "ipAddress": "10.0.0.15",
    "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) Edge/124.0.0.0",
    "timestamp": "2026-06-15T15:00:00Z",
    "resourceId": "thr_438",
    "resourceName": "Mass SQLi Campaign from 45.155.x.x",
    "action": "threat_resolved",
    "resourceType": "threat",
    "outcome": "success",
    "riskLevel": "low",
    "details": {
      "resolution": "IOCs published to MISP, blocking rules deployed",
      "ttc": "2h 45m"
    }
  },
  {
    "id": "al_0071",
    "userId": "usr_admin_001",
    "userEmail": "admin@honeyforge.io",
    "userRole": "admin",
    "ipAddress": "10.0.0.5",
    "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) Chrome/124.0.0.0 Safari/537.36",
    "timestamp": "2026-06-14T07:00:00Z",
    "sessionId": "sess_e001",
    "action": "login",
    "resourceType": "session",
    "outcome": "success",
    "riskLevel": "low",
    "details": {
      "mfa": true,
      "method": "totp"
    }
  },
  {
    "id": "al_0072",
    "userId": "usr_admin_001",
    "userEmail": "admin@honeyforge.io",
    "userRole": "admin",
    "ipAddress": "10.0.0.5",
    "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) Chrome/124.0.0.0 Safari/537.36",
    "timestamp": "2026-06-14T08:00:00Z",
    "resourceId": "usr_analyst_003",
    "resourceName": "mlee@honeyforge.io",
    "action": "user_created",
    "resourceType": "user",
    "outcome": "success",
    "riskLevel": "high",
    "details": {
      "role": "analyst",
      "mfa_required": true,
      "onboarded_by": "admin@honeyforge.io"
    }
  },
  {
    "id": "al_0073",
    "userId": "usr_analyst_002",
    "userEmail": "jsmith@honeyforge.io",
    "userRole": "analyst",
    "ipAddress": "10.0.0.8",
    "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) Firefox/125.0",
    "timestamp": "2026-06-14T08:30:00Z",
    "sessionId": "sess_e002",
    "action": "login",
    "resourceType": "session",
    "outcome": "success",
    "riskLevel": "low",
    "details": {
      "mfa": true,
      "method": "totp"
    }
  },
  {
    "id": "al_0074",
    "userId": "usr_analyst_002",
    "userEmail": "jsmith@honeyforge.io",
    "userRole": "analyst",
    "ipAddress": "10.0.0.8",
    "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) Firefox/125.0",
    "timestamp": "2026-06-14T09:00:00Z",
    "resourceId": "r_019",
    "resourceName": "Python ReverseShell via SSH",
    "action": "rule_created",
    "resourceType": "rule",
    "outcome": "success",
    "riskLevel": "medium",
    "details": {
      "type": "sigma",
      "severity": "high",
      "mitre": "T1059.006"
    }
  },
  {
    "id": "al_0075",
    "userId": "usr_admin_001",
    "userEmail": "admin@honeyforge.io",
    "userRole": "admin",
    "ipAddress": "10.0.0.5",
    "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) Chrome/124.0.0.0 Safari/537.36",
    "timestamp": "2026-06-14T10:00:00Z",
    "resourceId": "int_s3",
    "resourceName": "S3-Compatible Storage",
    "action": "integration_configured",
    "resourceType": "integration",
    "outcome": "success",
    "riskLevel": "high",
    "details": {
      "changes": [
        "bucket: hf-logs-dev → hf-logs-prod",
        "encryption: off → AES-256"
      ]
    }
  },
  {
    "id": "al_0076",
    "userId": "usr_analyst_001",
    "userEmail": "analyst@honeyforge.io",
    "userRole": "analyst",
    "ipAddress": "10.0.0.15",
    "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) Edge/124.0.0.0",
    "timestamp": "2026-06-14T10:30:00Z",
    "resourceId": "evt_8750",
    "resourceName": "MongoDB NoSQL Injection — 91.108.4.41",
    "action": "event_marked_attack",
    "resourceType": "event",
    "outcome": "success",
    "riskLevel": "low",
    "details": {
      "confidence": "high",
      "mitre": "T1190",
      "port": 27017
    }
  },
  {
    "id": "al_0077",
    "userId": "usr_admin_001",
    "userEmail": "admin@honeyforge.io",
    "userRole": "admin",
    "ipAddress": "10.0.0.5",
    "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) Chrome/124.0.0.0 Safari/537.36",
    "timestamp": "2026-06-14T11:00:00Z",
    "action": "clone_studio_changed",
    "resourceType": "clone-studio",
    "outcome": "success",
    "riskLevel": "medium",
    "details": {
      "changes": [
        "global_response_delay: 50ms → 200ms",
        "simulate_packet_loss: false → true"
      ]
    }
  },
  {
    "id": "al_0078",
    "userId": "usr_analyst_002",
    "userEmail": "jsmith@honeyforge.io",
    "userRole": "analyst",
    "ipAddress": "10.0.0.8",
    "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) Firefox/125.0",
    "timestamp": "2026-06-14T11:30:00Z",
    "action": "ioc_exported",
    "resourceType": "ioc",
    "outcome": "success",
    "riskLevel": "medium",
    "details": {
      "count": 9,
      "format": "CSV",
      "destination": "CrowdStrike Falcon",
      "tlp": "WHITE"
    }
  },
  {
    "id": "al_0079",
    "userId": "usr_analyst_003",
    "userEmail": "mlee@honeyforge.io",
    "userRole": "analyst",
    "ipAddress": "10.0.0.12",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 14_5) Chrome/124.0.0.0 Safari/537.36",
    "timestamp": "2026-06-14T12:00:00Z",
    "sessionId": "sess_e003",
    "action": "login",
    "resourceType": "session",
    "outcome": "success",
    "riskLevel": "low",
    "details": {
      "mfa": true,
      "method": "totp"
    }
  },
  {
    "id": "al_0080",
    "userId": "usr_admin_001",
    "userEmail": "admin@honeyforge.io",
    "userRole": "admin",
    "ipAddress": "10.0.0.5",
    "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) Chrome/124.0.0.0 Safari/537.36",
    "timestamp": "2026-06-14T14:00:00Z",
    "resourceId": "d_010",
    "resourceName": "HoneD-RDP-US-02",
    "action": "decoy_created",
    "resourceType": "decoy",
    "outcome": "success",
    "riskLevel": "medium",
    "details": {
      "type": "rdp",
      "port": 3389,
      "region": "us-east-1",
      "template": "windows-2019-vanilla"
    }
  },
  {
    "id": "al_0081",
    "userId": "usr_admin_001",
    "userEmail": "admin@honeyforge.io",
    "userRole": "admin",
    "ipAddress": "10.0.0.5",
    "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) Chrome/124.0.0.0 Safari/537.36",
    "timestamp": "2026-06-13T07:00:00Z",
    "sessionId": "sess_f001",
    "action": "login",
    "resourceType": "session",
    "outcome": "success",
    "riskLevel": "low",
    "details": {
      "mfa": true,
      "method": "totp"
    }
  },
  {
    "id": "al_0082",
    "userId": "usr_admin_001",
    "userEmail": "admin@honeyforge.io",
    "userRole": "admin",
    "ipAddress": "10.0.0.5",
    "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) Chrome/124.0.0.0 Safari/537.36",
    "timestamp": "2026-06-13T08:00:00Z",
    "action": "settings_changed",
    "resourceType": "settings",
    "outcome": "success",
    "riskLevel": "high",
    "details": {
      "key": "siem_forwarding_enabled",
      "from": false,
      "to": true,
      "reason": "New OpenSearch cluster ready"
    }
  },
  {
    "id": "al_0083",
    "userId": "usr_analyst_002",
    "userEmail": "jsmith@honeyforge.io",
    "userRole": "analyst",
    "ipAddress": "10.0.0.8",
    "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) Firefox/125.0",
    "timestamp": "2026-06-13T08:30:00Z",
    "sessionId": "sess_f002",
    "action": "login",
    "resourceType": "session",
    "outcome": "success",
    "riskLevel": "low",
    "details": {
      "mfa": true,
      "method": "totp"
    }
  },
  {
    "id": "al_0084",
    "userId": "usr_admin_001",
    "userEmail": "admin@honeyforge.io",
    "userRole": "admin",
    "ipAddress": "10.0.0.5",
    "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) Chrome/124.0.0.0 Safari/537.36",
    "timestamp": "2026-06-13T09:00:00Z",
    "resourceId": "int_legacy",
    "resourceName": "Legacy Syslog Export",
    "action": "integration_removed",
    "resourceType": "integration",
    "outcome": "success",
    "riskLevel": "high",
    "details": {
      "reason": "Decommissioned — replaced by OpenSearch direct feed",
      "decommissionedBy": "admin@honeyforge.io"
    }
  },
  {
    "id": "al_0085",
    "userId": "usr_analyst_002",
    "userEmail": "jsmith@honeyforge.io",
    "userRole": "analyst",
    "ipAddress": "10.0.0.8",
    "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) Firefox/125.0",
    "timestamp": "2026-06-13T09:30:00Z",
    "resourceId": "r_015",
    "resourceName": "ICMP Ping Sweep Detection",
    "action": "rule_enabled",
    "resourceType": "rule",
    "outcome": "success",
    "riskLevel": "medium",
    "details": {
      "previousStatus": "disabled",
      "reason": "Internal network expanded to /16"
    }
  },
  {
    "id": "al_0086",
    "userId": "usr_analyst_003",
    "userEmail": "mlee@honeyforge.io",
    "userRole": "analyst",
    "ipAddress": "10.0.0.12",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 14_5) Chrome/124.0.0.0 Safari/537.36",
    "timestamp": "2026-06-13T10:00:00Z",
    "sessionId": "sess_f003",
    "action": "login",
    "resourceType": "session",
    "outcome": "success",
    "riskLevel": "low",
    "details": {
      "mfa": true,
      "method": "totp"
    }
  },
  {
    "id": "al_0087",
    "userId": "usr_analyst_003",
    "userEmail": "mlee@honeyforge.io",
    "userRole": "analyst",
    "ipAddress": "10.0.0.12",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 14_5) Chrome/124.0.0.0 Safari/537.36",
    "timestamp": "2026-06-13T10:30:00Z",
    "resourceId": "evt_8730",
    "resourceName": "Eternal Blue Probe — 198.54.117.212",
    "action": "event_marked_attack",
    "resourceType": "event",
    "outcome": "success",
    "riskLevel": "low",
    "details": {
      "confidence": "critical",
      "cve": "MS17-010",
      "mitre": "T1210"
    }
  },
  {
    "id": "al_0088",
    "userId": "usr_analyst_001",
    "userEmail": "analyst@honeyforge.io",
    "userRole": "analyst",
    "ipAddress": "10.0.0.15",
    "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) Edge/124.0.0.0",
    "timestamp": "2026-06-13T11:00:00Z",
    "sessionId": "sess_f004",
    "action": "login",
    "resourceType": "session",
    "outcome": "success",
    "riskLevel": "low",
    "details": {
      "mfa": true,
      "method": "totp"
    }
  },
  {
    "id": "al_0089",
    "userId": "usr_admin_001",
    "userEmail": "admin@honeyforge.io",
    "userRole": "admin",
    "ipAddress": "10.0.0.5",
    "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) Chrome/124.0.0.0 Safari/537.36",
    "timestamp": "2026-06-13T12:00:00Z",
    "resourceId": "usr_analyst_001",
    "resourceName": "analyst@honeyforge.io",
    "action": "role_changed",
    "resourceType": "user",
    "outcome": "success",
    "riskLevel": "critical",
    "details": {
      "from": "analyst",
      "to": "admin",
      "reason": "Promoted to SOC lead after onboarding period"
    }
  },
  {
    "id": "al_0090",
    "userId": "usr_analyst_002",
    "userEmail": "jsmith@honeyforge.io",
    "userRole": "analyst",
    "ipAddress": "10.0.0.8",
    "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) Firefox/125.0",
    "timestamp": "2026-06-13T14:00:00Z",
    "resourceId": "thr_437",
    "resourceName": "Mirai Botnet C2 Callbacks",
    "action": "threat_assigned",
    "resourceType": "threat",
    "outcome": "success",
    "riskLevel": "low",
    "details": {
      "assignedTo": "analyst@honeyforge.io",
      "priority": "high"
    }
  },
  {
    "id": "al_0091",
    "userId": "usr_admin_001",
    "userEmail": "admin@honeyforge.io",
    "userRole": "admin",
    "ipAddress": "10.0.0.5",
    "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) Chrome/124.0.0.0 Safari/537.36",
    "timestamp": "2026-06-13T17:30:00Z",
    "sessionId": "sess_f001",
    "action": "logout",
    "resourceType": "session",
    "outcome": "success",
    "riskLevel": "low",
    "details": {
      "duration": "10h 30m"
    }
  },
  {
    "id": "al_0092",
    "userId": "usr_admin_001",
    "userEmail": "admin@honeyforge.io",
    "userRole": "admin",
    "ipAddress": "10.0.0.5",
    "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) Chrome/124.0.0.0 Safari/537.36",
    "timestamp": "2026-06-12T07:00:00Z",
    "sessionId": "sess_g001",
    "action": "login",
    "resourceType": "session",
    "outcome": "success",
    "riskLevel": "low",
    "details": {
      "mfa": true,
      "method": "totp"
    }
  },
  {
    "id": "al_0093",
    "userId": "usr_admin_001",
    "userEmail": "admin@honeyforge.io",
    "userRole": "admin",
    "ipAddress": "10.0.0.5",
    "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) Chrome/124.0.0.0 Safari/537.36",
    "timestamp": "2026-06-12T08:00:00Z",
    "resourceId": "usr_viewer_002",
    "resourceName": "contractor1@honeyforge.io",
    "action": "user_deleted",
    "resourceType": "user",
    "outcome": "success",
    "riskLevel": "critical",
    "details": {
      "reason": "Contract ended — access revoked per offboarding policy",
      "deletedBy": "admin@honeyforge.io"
    }
  },
  {
    "id": "al_0094",
    "userId": "usr_analyst_002",
    "userEmail": "jsmith@honeyforge.io",
    "userRole": "analyst",
    "ipAddress": "10.0.0.8",
    "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) Firefox/125.0",
    "timestamp": "2026-06-12T09:00:00Z",
    "sessionId": "sess_g002",
    "action": "login",
    "resourceType": "session",
    "outcome": "success",
    "riskLevel": "low",
    "details": {
      "mfa": true,
      "method": "totp"
    }
  },
  {
    "id": "al_0095",
    "userId": "usr_admin_001",
    "userEmail": "admin@honeyforge.io",
    "userRole": "admin",
    "ipAddress": "10.0.0.5",
    "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) Chrome/124.0.0.0 Safari/537.36",
    "timestamp": "2026-06-12T09:30:00Z",
    "resourceId": "d_009",
    "resourceName": "Heralding-SMB-AS-01",
    "action": "decoy_created",
    "resourceType": "decoy",
    "outcome": "success",
    "riskLevel": "medium",
    "details": {
      "type": "smb",
      "port": 445,
      "region": "ap-south-1",
      "template": "heralding-smb"
    }
  },
  {
    "id": "al_0096",
    "userId": "usr_analyst_003",
    "userEmail": "mlee@honeyforge.io",
    "userRole": "analyst",
    "ipAddress": "10.0.0.12",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 14_5) Chrome/124.0.0.0 Safari/537.36",
    "timestamp": "2026-06-12T10:00:00Z",
    "sessionId": "sess_g003",
    "action": "login",
    "resourceType": "session",
    "outcome": "success",
    "riskLevel": "low",
    "details": {
      "mfa": true,
      "method": "totp"
    }
  },
  {
    "id": "al_0097",
    "userId": "usr_analyst_002",
    "userEmail": "jsmith@honeyforge.io",
    "userRole": "analyst",
    "ipAddress": "10.0.0.8",
    "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) Firefox/125.0",
    "timestamp": "2026-06-12T10:30:00Z",
    "resourceId": "evt_8700",
    "resourceName": "WannaCry Signature Match — 92.63.194.10",
    "action": "event_marked_attack",
    "resourceType": "event",
    "outcome": "success",
    "riskLevel": "low",
    "details": {
      "confidence": "critical",
      "cve": "MS17-010",
      "mitre": "T1486",
      "iocs": [
        "92.63.194.10"
      ]
    }
  },
  {
    "id": "al_0098",
    "userId": "usr_admin_001",
    "userEmail": "admin@honeyforge.io",
    "userRole": "admin",
    "ipAddress": "10.0.0.5",
    "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) Chrome/124.0.0.0 Safari/537.36",
    "timestamp": "2026-06-12T11:00:00Z",
    "resourceId": "int_misp",
    "resourceName": "MISP Threat Intel",
    "action": "integration_configured",
    "resourceType": "integration",
    "outcome": "success",
    "riskLevel": "high",
    "details": {
      "changes": [
        "sharing_group: SECTOR → OPSEC",
        "auto_publish: false → true"
      ]
    }
  },
  {
    "id": "al_0099",
    "userId": "usr_analyst_003",
    "userEmail": "mlee@honeyforge.io",
    "userRole": "analyst",
    "ipAddress": "10.0.0.12",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 14_5) Chrome/124.0.0.0 Safari/537.36",
    "timestamp": "2026-06-12T12:00:00Z",
    "action": "ioc_exported",
    "resourceType": "ioc",
    "outcome": "success",
    "riskLevel": "medium",
    "details": {
      "count": 41,
      "format": "STIX 2.1",
      "destination": "MISP",
      "tlp": "AMBER"
    }
  },
  {
    "id": "al_0100",
    "userId": "usr_analyst_002",
    "userEmail": "jsmith@honeyforge.io",
    "userRole": "analyst",
    "ipAddress": "10.0.0.8",
    "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) Firefox/125.0",
    "timestamp": "2026-06-12T14:00:00Z",
    "resourceId": "rep_mitre",
    "resourceName": "MITRE ATT&CK Coverage Report",
    "action": "report_generated",
    "resourceType": "report",
    "outcome": "success",
    "riskLevel": "low",
    "details": {
      "format": "pdf",
      "fileSize": 2108234,
      "period": "30d"
    }
  },
  {
    "id": "al_0101",
    "userId": "usr_admin_001",
    "userEmail": "admin@honeyforge.io",
    "userRole": "admin",
    "ipAddress": "10.0.0.5",
    "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) Chrome/124.0.0.0 Safari/537.36",
    "timestamp": "2026-06-12T16:00:00Z",
    "action": "settings_changed",
    "resourceType": "settings",
    "outcome": "success",
    "riskLevel": "high",
    "details": {
      "key": "max_concurrent_sessions",
      "from": 3,
      "to": 2,
      "reason": "Enforce principle of least privilege"
    }
  },
  {
    "id": "al_0102",
    "userId": "usr_admin_001",
    "userEmail": "admin@honeyforge.io",
    "userRole": "admin",
    "ipAddress": "10.0.0.5",
    "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) Chrome/124.0.0.0 Safari/537.36",
    "timestamp": "2026-06-12T17:00:00Z",
    "sessionId": "sess_g001",
    "action": "logout",
    "resourceType": "session",
    "outcome": "success",
    "riskLevel": "low",
    "details": {
      "duration": "10h 00m"
    }
  }
]

// Legacy compat
export const AUDIT_LOG_COUNT = 102
